import { BibleBook } from '../types/bible';

export const BIBLE_BOOKS: BibleBook[] = [
  { id: 1, name: 'Genesis', testament: 'Old Testament', chapterCount: 50, bookOrder: 1 },
  { id: 2, name: 'Exodus', testament: 'Old Testament', chapterCount: 40, bookOrder: 2 },
  { id: 3, name: 'Leviticus', testament: 'Old Testament', chapterCount: 27, bookOrder: 3 },
  { id: 4, name: 'Numbers', testament: 'Old Testament', chapterCount: 36, bookOrder: 4 },
  { id: 5, name: 'Deuteronomy', testament: 'Old Testament', chapterCount: 34, bookOrder: 5 },
  { id: 6, name: 'Joshua', testament: 'Old Testament', chapterCount: 24, bookOrder: 6 },
  { id: 7, name: 'Judges', testament: 'Old Testament', chapterCount: 21, bookOrder: 7 },
  { id: 8, name: 'Ruth', testament: 'Old Testament', chapterCount: 4, bookOrder: 8 },
  { id: 9, name: '1 Samuel', testament: 'Old Testament', chapterCount: 31, bookOrder: 9 },
  { id: 10, name: '2 Samuel', testament: 'Old Testament', chapterCount: 24, bookOrder: 10 },
  { id: 11, name: '1 Kings', testament: 'Old Testament', chapterCount: 22, bookOrder: 11 },
  { id: 12, name: '2 Kings', testament: 'Old Testament', chapterCount: 25, bookOrder: 12 },
  { id: 13, name: '1 Chronicles', testament: 'Old Testament', chapterCount: 29, bookOrder: 13 },
  { id: 14, name: '2 Chronicles', testament: 'Old Testament', chapterCount: 36, bookOrder: 14 },
  { id: 15, name: 'Ezra', testament: 'Old Testament', chapterCount: 10, bookOrder: 15 },
  { id: 16, name: 'Nehemiah', testament: 'Old Testament', chapterCount: 13, bookOrder: 16 },
  { id: 17, name: 'Esther', testament: 'Old Testament', chapterCount: 10, bookOrder: 17 },
  { id: 18, name: 'Job', testament: 'Old Testament', chapterCount: 42, bookOrder: 18 },
  { id: 19, name: 'Psalms', testament: 'Old Testament', chapterCount: 150, bookOrder: 19 },
  { id: 20, name: 'Proverbs', testament: 'Old Testament', chapterCount: 31, bookOrder: 20 },
  { id: 21, name: 'Ecclesiastes', testament: 'Old Testament', chapterCount: 12, bookOrder: 21 },
  { id: 22, name: 'Song of Solomon', testament: 'Old Testament', chapterCount: 8, bookOrder: 22 },
  { id: 23, name: 'Isaiah', testament: 'Old Testament', chapterCount: 66, bookOrder: 23 },
  { id: 24, name: 'Jeremiah', testament: 'Old Testament', chapterCount: 52, bookOrder: 24 },
  { id: 25, name: 'Lamentations', testament: 'Old Testament', chapterCount: 5, bookOrder: 25 },
  { id: 26, name: 'Ezekiel', testament: 'Old Testament', chapterCount: 48, bookOrder: 26 },
  { id: 27, name: 'Daniel', testament: 'Old Testament', chapterCount: 12, bookOrder: 27 },
  { id: 28, name: 'Hosea', testament: 'Old Testament', chapterCount: 14, bookOrder: 28 },
  { id: 29, name: 'Joel', testament: 'Old Testament', chapterCount: 3, bookOrder: 29 },
  { id: 30, name: 'Amos', testament: 'Old Testament', chapterCount: 9, bookOrder: 30 },
  { id: 31, name: 'Obadiah', testament: 'Old Testament', chapterCount: 1, bookOrder: 31 },
  { id: 32, name: 'Jonah', testament: 'Old Testament', chapterCount: 4, bookOrder: 32 },
  { id: 33, name: 'Micah', testament: 'Old Testament', chapterCount: 7, bookOrder: 33 },
  { id: 34, name: 'Nahum', testament: 'Old Testament', chapterCount: 3, bookOrder: 34 },
  { id: 35, name: 'Habakkuk', testament: 'Old Testament', chapterCount: 3, bookOrder: 35 },
  { id: 36, name: 'Zephaniah', testament: 'Old Testament', chapterCount: 3, bookOrder: 36 },
  { id: 37, name: 'Haggai', testament: 'Old Testament', chapterCount: 2, bookOrder: 37 },
  { id: 38, name: 'Zechariah', testament: 'Old Testament', chapterCount: 14, bookOrder: 38 },
  { id: 39, name: 'Malachi', testament: 'Old Testament', chapterCount: 4, bookOrder: 39 },
  { id: 40, name: 'Matthew', testament: 'New Testament', chapterCount: 28, bookOrder: 40 },
  { id: 41, name: 'Mark', testament: 'New Testament', chapterCount: 16, bookOrder: 41 },
  { id: 42, name: 'Luke', testament: 'New Testament', chapterCount: 24, bookOrder: 42 },
  { id: 43, name: 'John', testament: 'New Testament', chapterCount: 21, bookOrder: 43 },
  { id: 44, name: 'Acts', testament: 'New Testament', chapterCount: 28, bookOrder: 44 },
  { id: 45, name: 'Romans', testament: 'New Testament', chapterCount: 16, bookOrder: 45 },
  { id: 46, name: '1 Corinthians', testament: 'New Testament', chapterCount: 16, bookOrder: 46 },
  { id: 47, name: '2 Corinthians', testament: 'New Testament', chapterCount: 13, bookOrder: 47 },
  { id: 48, name: 'Galatians', testament: 'New Testament', chapterCount: 6, bookOrder: 48 },
  { id: 49, name: 'Ephesians', testament: 'New Testament', chapterCount: 6, bookOrder: 49 },
  { id: 50, name: 'Philippians', testament: 'New Testament', chapterCount: 4, bookOrder: 50 },
  { id: 51, name: 'Colossians', testament: 'New Testament', chapterCount: 4, bookOrder: 51 },
  { id: 52, name: '1 Thessalonians', testament: 'New Testament', chapterCount: 5, bookOrder: 52 },
  { id: 53, name: '2 Thessalonians', testament: 'New Testament', chapterCount: 3, bookOrder: 53 },
  { id: 54, name: '1 Timothy', testament: 'New Testament', chapterCount: 6, bookOrder: 54 },
  { id: 55, name: '2 Timothy', testament: 'New Testament', chapterCount: 4, bookOrder: 55 },
  { id: 56, name: 'Titus', testament: 'New Testament', chapterCount: 3, bookOrder: 56 },
  { id: 57, name: 'Philemon', testament: 'New Testament', chapterCount: 1, bookOrder: 57 },
  { id: 58, name: 'Hebrews', testament: 'New Testament', chapterCount: 13, bookOrder: 58 },
  { id: 59, name: 'James', testament: 'New Testament', chapterCount: 5, bookOrder: 59 },
  { id: 60, name: '1 Peter', testament: 'New Testament', chapterCount: 5, bookOrder: 60 },
  { id: 61, name: '2 Peter', testament: 'New Testament', chapterCount: 3, bookOrder: 61 },
  { id: 62, name: '1 John', testament: 'New Testament', chapterCount: 5, bookOrder: 62 },
  { id: 63, name: '2 John', testament: 'New Testament', chapterCount: 1, bookOrder: 63 },
  { id: 64, name: '3 John', testament: 'New Testament', chapterCount: 1, bookOrder: 64 },
  { id: 65, name: 'Jude', testament: 'New Testament', chapterCount: 1, bookOrder: 65 },
  { id: 66, name: 'Revelation', testament: 'New Testament', chapterCount: 22, bookOrder: 66 },
];
